language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g bower grunt-cli
install:
  - npm install
  - bower install
script:
  - grunt test:development
  - grunt test
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
